export { default as PostButton } from "./PostButton/PostButton";
export { default as PostComments } from "./PostComments/PostComments";
export { default as PostImage } from "./PostImage/PostImage";
export { default as PostText } from "./PostText/PostText";
export { default as FollowButton } from "./FollowButton/FollowButton";
export { CommentsButton, LikesButton } from "./IconButtons";
export { default as UserAvatar } from "./UserAvatar/UserAvatar";
export { default as PostDate } from "./PostDate/PostDate";
export { default as PostTitle } from "./PostTitle/PostTitle";
export { default as PostFullName } from "./PostFullName/PostFullName";
export { default as UserNickName } from "./UserNickName/UserNickName";
