export enum IconEnum {
  Eye_Off = "eye-off",
  Eye = "eye",
  Facebook = "facebook",
  Google = "google",
  Twitter = "twitter",
  Ok = "Ok",
  User = "user",
  Notification = "notification",
  Home = "home",
  Search = "search",
  Settings = "settings",
  SignOut = "sign-out",
  Menu = "menu",
  Cross = "cross",
  ArrowRight = "arrow-right",
  AddPost = "add-post",
  EditProfile = "edit-profile",
  Location = "location-icon",
  Camera = "camera",
  Edit = "edit",
  Save = "save",
}
