export { default as WelcomePage } from "./WelcomePage/WelcomePage";
export { default as RegisterPage } from "./RegisterPage/RegisterPage";
export { default as AccountCreationPage } from "./AccountCreationPage/AccountCreationPage";
export { default as LoginPage } from "./LoginPage/LoginPage";
export { default as ErrorPage } from "./ErrorPage/ErrorPage";
export { default as ForgotPasswordPage } from "./ForgotPasswordPage/ForgotPasswordPage";
export { default as UIPage } from "./UIPage/UIPage";
export { default as FeedPage } from "./FeedPage/FeedPage";
export { default as SettingsPage } from "./SettingsPage/SettingsPage";
