export enum links {
  HOME = "/",
  AUTH = "/auth",
  SIGN_UP = "/auth/register",
  ACCOUNT_CREATION = "/auth/account-creation",
  LOG_IN = "/auth/login",
  FORGOT_PASSWORD = "/auth/forgot-password",
  RESTORE = "/auth/restore",
  FEED = "/feed",
  SETTINGS = "/settings",
  NOT_FOUND = "/404",
  PASSWORD_CHANGE = "/auth/password-change",
  PROFILE = "/profile",
  GUEST_PROFILE = "/:Id",
  USER_BOOKS = "/books",
  SEARCH = "/search",
  GUEST_BOOKS = "/:id/books",
  NOTIFICATION = "/notifications",
  GUEST_POST = "/post/:id",
  MESSAGES = "/messages",
  TERMS = "/terms",
}
