name: Chapter Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build-and-deploy:
    uses: DenysHalkin/chapter-github-templates/.github/workflows/frontend_ci_cd.yml@main
    with:
      ENVIRONMENT: ${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}


